### ISSUE TITLE
freebsd的兼容性问题

### ISSUE THREAD

**Issue by bingloo** [Calcium-Ion/new-api#614]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

从`v0.3.1.4`后，freebsd就不能用了，能兼容下吗谢谢。

错误信息：

```
goroutine 1 [running]:
github.com/bytedance/sonic/loader.mmap(0x86c12e588?)
	/root/go/pkg/mod/github.com/bytedance/sonic/loader@v0.2.1/mmap_unix.go:35 +0x7b
github.com/bytedance/sonic/loader.makeModuledata({0x483b05, 0x7}, {0x86c149d10, 0x1, 0x1ba47bd?}, 0x86c149a80, {0x333d720, 0x4dc0, 0x1?})
	/root/go/pkg/mod/github.com/bytedance/sonic/loader@v0.2.1/funcdata_latest.go:228 +0x370
github.com/bytedance/sonic/loader.Load({0x333d720, 0x4dc0, 0x4dc0}, {0x86c12e588, 0x3, 0x3}, {0x483b05, 0x7}, {0x86c149d10, 0x1, ...})
	/root/go/pkg/mod/github.com/bytedance/sonic/loader@v0.2.1/loader_latest.go:93 +0x16c
github.com/bytedance/sonic/loader.WrapGoC({0x333d720, 0x4dc0, 0x4dc0}, {0x324ef60, 0x3, 0x98?}, {0x324c1a0, 0x2, 0x249ad9f?}, {0x483b05, ...}, ...)
	/root/go/pkg/mod/github.com/bytedance/sonic/loader@v0.2.1/wrapper.go:102 +0x496
github.com/cloudwego/base64x.init.0()
	/root/go/pkg/mod/github.com/cloudwego/base64x@v0.1.4/native_amd64.go:57 +0x93
```

**复现步骤**

使用最新代码编译并运行。

**预期结果**

正常使用。

**Comment by Calcium-Ion** [comment]
你试一下最新代码行不行

**Comment by bingloo** [comment]
> 你试一下最新代码行不行

你好，测试了最新`v0.3.3.6`正常，谢谢。
