### ISSUE TITLE
进入设置页面会白屏并报错

### ISSUE THREAD

**Issue by chchchchc1023** [Calcium-Ion/new-api#675]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
进入设置页面白屏报错如下：
react-core-BI8elXsy.js:32 TypeError: Cannot read properties of null (reading 'length')
    at Cs (index-ujcwpg9C.js:2:65719)
    at Oo (react-core-BI8elXsy.js:30:16959)
    at Fi (react-core-BI8elXsy.js:32:3134)
    at Ec (react-core-BI8elXsy.js:32:44485)
    at wc (react-core-BI8elXsy.js:32:39513)
    at Yd (react-core-BI8elXsy.js:32:39444)
    at ul (react-core-BI8elXsy.js:32:39302)
    at Yi (react-core-BI8elXsy.js:32:35719)
    at vc (react-core-BI8elXsy.js:32:34675)
    at k (react-core-BI8elXsy.js:17:1562)

react-core-BI8elXsy.js:32 Uncaught TypeError: Cannot read properties of null (reading 'length')
    at Cs (index-ujcwpg9C.js:2:65719)
    at Oo (react-core-BI8elXsy.js:30:16959)
    at Fi (react-core-BI8elXsy.js:32:3134)
    at Ec (react-core-BI8elXsy.js:32:44485)
    at wc (react-core-BI8elXsy.js:32:39513)
    at Yd (react-core-BI8elXsy.js:32:39444)
    at ul (react-core-BI8elXsy.js:32:39302)
    at Yi (react-core-BI8elXsy.js:32:35719)
    at vc (react-core-BI8elXsy.js:32:34675)
    at k (react-core-BI8elXsy.js:17:1562)
**复现步骤**
重新部署后依旧
**预期结果**
正确进入设置页面
**相关截图**
<img width="1503" alt="image" src="https://github.com/user-attachments/assets/adede428-d734-4a49-a0a0-61eaf970defc" />
<img width="485" alt="image" src="https://github.com/user-attachments/assets/a3967336-c7b7-425a-b662-abeea9052da3" />

**Comment by Calcium-Ion** [comment]
已经修复了，请等待发版



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月29日(周日) 中午11:43
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Calcium-Ion/new-api] 进入设置页面会白屏并报错 (Issue #675)




 
例行检查
  
 我已确认目前没有类似 issue
 
 我已确认我已升级到最新版本
 
 我已完整查看过项目 README，尤其是常见问题部分
 
 我理解并愿意跟进此 issue，协助测试和提供反馈
 
 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭
  
问题描述
 进入设置页面白屏报错如下：
 react-core-BI8elXsy.js:32 TypeError: Cannot read properties of null (reading 'length')
 at Cs (index-ujcwpg9C.js:2:65719)
 at Oo (react-core-BI8elXsy.js:30:16959)
 at Fi (react-core-BI8elXsy.js:32:3134)
 at Ec (react-core-BI8elXsy.js:32:44485)
 at wc (react-core-BI8elXsy.js:32:39513)
 at Yd (react-core-BI8elXsy.js:32:39444)
 at ul (react-core-BI8elXsy.js:32:39302)
 at Yi (react-core-BI8elXsy.js:32:35719)
 at vc (react-core-BI8elXsy.js:32:34675)
 at k (react-core-BI8elXsy.js:17:1562)
 
react-core-BI8elXsy.js:32 Uncaught TypeError: Cannot read properties of null (reading 'length')
 at Cs (index-ujcwpg9C.js:2:65719)
 at Oo (react-core-BI8elXsy.js:30:16959)
 at Fi (react-core-BI8elXsy.js:32:3134)
 at Ec (react-core-BI8elXsy.js:32:44485)
 at wc (react-core-BI8elXsy.js:32:39513)
 at Yd (react-core-BI8elXsy.js:32:39444)
 at ul (react-core-BI8elXsy.js:32:39302)
 at Yi (react-core-BI8elXsy.js:32:35719)
 at vc (react-core-BI8elXsy.js:32:34675)
 at k (react-core-BI8elXsy.js:17:1562)
 复现步骤
 重新部署后依旧
 预期结果
 正确进入设置页面
 相关截图
 image.png (view on web)
 image.png (view on web)
